name: IGTD
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.2.1
  - numpy=1.18.1
  - pandas=0.25.3
  - scipy=1.3.1
  - keras=2.2.4
  - scikit-learn=0.21.2
  - tensorflow=1.14.0
  - tensorflow-gpu=1.14.0
